/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FundingEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelProject"
      | "cancelled"
      | "contributions"
      | "currentStage"
      | "deadline"
      | "donate"
      | "fundingGoal"
      | "fundsRaised"
      | "getStageAllocation"
      | "governance"
      | "isStageReleased"
      | "projectOwner"
      | "refund"
      | "refunded"
      | "refundsEnabled"
      | "releaseFunds"
      | "setGovernance"
      | "totalReleased"
      | "totalStages"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundingGoalReached"
      | "FundsDonated"
      | "GovernanceUpdated"
      | "MilestoneFundsReleased"
      | "ProjectCancelled"
      | "RefundClaimed"
      | "RefundsEnabled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelProject",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cancelled", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentStage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(functionFragment: "donate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundingGoal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundsRaised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStageAllocation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isStageReleased",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refunded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundsEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStages",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundingGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundsRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStageAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isStageReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refunded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundsEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStages",
    data: BytesLike
  ): Result;
}

export namespace FundingGoalReachedEvent {
  export type InputTuple = [totalRaised: BigNumberish];
  export type OutputTuple = [totalRaised: bigint];
  export interface OutputObject {
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDonatedEvent {
  export type InputTuple = [
    donor: AddressLike,
    amount: BigNumberish,
    totalRaised: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    amount: bigint,
    totalRaised: bigint
  ];
  export interface OutputObject {
    donor: string;
    amount: bigint;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceUpdatedEvent {
  export type InputTuple = [governance: AddressLike];
  export type OutputTuple = [governance: string];
  export interface OutputObject {
    governance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneFundsReleasedEvent {
  export type InputTuple = [
    stageIndex: BigNumberish,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    stageIndex: bigint,
    amount: bigint,
    recipient: string
  ];
  export interface OutputObject {
    stageIndex: bigint;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCancelledEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [donor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [donor: string, amount: bigint];
  export interface OutputObject {
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundsEnabledEvent {
  export type InputTuple = [refundPool: BigNumberish];
  export type OutputTuple = [refundPool: bigint];
  export interface OutputObject {
    refundPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundingEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): FundingEscrow;
  waitForDeployment(): Promise<this>;

  interface: FundingEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelProject: TypedContractMethod<[], [void], "nonpayable">;

  cancelled: TypedContractMethod<[], [boolean], "view">;

  contributions: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  currentStage: TypedContractMethod<[], [bigint], "view">;

  deadline: TypedContractMethod<[], [bigint], "view">;

  donate: TypedContractMethod<[], [void], "payable">;

  fundingGoal: TypedContractMethod<[], [bigint], "view">;

  fundsRaised: TypedContractMethod<[], [bigint], "view">;

  getStageAllocation: TypedContractMethod<
    [stageIndex: BigNumberish],
    [bigint],
    "view"
  >;

  governance: TypedContractMethod<[], [string], "view">;

  isStageReleased: TypedContractMethod<
    [stageIndex: BigNumberish],
    [boolean],
    "view"
  >;

  projectOwner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  refunded: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  refundsEnabled: TypedContractMethod<[], [boolean], "view">;

  releaseFunds: TypedContractMethod<
    [stageIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGovernance: TypedContractMethod<
    [_governance: AddressLike],
    [void],
    "nonpayable"
  >;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  totalStages: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelProject"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentStage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fundingGoal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundsRaised"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStageAllocation"
  ): TypedContractMethod<[stageIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isStageReleased"
  ): TypedContractMethod<[stageIndex: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "projectOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refunded"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundsEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[stageIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGovernance"
  ): TypedContractMethod<[_governance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStages"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FundingGoalReached"
  ): TypedContractEvent<
    FundingGoalReachedEvent.InputTuple,
    FundingGoalReachedEvent.OutputTuple,
    FundingGoalReachedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDonated"
  ): TypedContractEvent<
    FundsDonatedEvent.InputTuple,
    FundsDonatedEvent.OutputTuple,
    FundsDonatedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceUpdated"
  ): TypedContractEvent<
    GovernanceUpdatedEvent.InputTuple,
    GovernanceUpdatedEvent.OutputTuple,
    GovernanceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneFundsReleased"
  ): TypedContractEvent<
    MilestoneFundsReleasedEvent.InputTuple,
    MilestoneFundsReleasedEvent.OutputTuple,
    MilestoneFundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCancelled"
  ): TypedContractEvent<
    ProjectCancelledEvent.InputTuple,
    ProjectCancelledEvent.OutputTuple,
    ProjectCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RefundsEnabled"
  ): TypedContractEvent<
    RefundsEnabledEvent.InputTuple,
    RefundsEnabledEvent.OutputTuple,
    RefundsEnabledEvent.OutputObject
  >;

  filters: {
    "FundingGoalReached(uint256)": TypedContractEvent<
      FundingGoalReachedEvent.InputTuple,
      FundingGoalReachedEvent.OutputTuple,
      FundingGoalReachedEvent.OutputObject
    >;
    FundingGoalReached: TypedContractEvent<
      FundingGoalReachedEvent.InputTuple,
      FundingGoalReachedEvent.OutputTuple,
      FundingGoalReachedEvent.OutputObject
    >;

    "FundsDonated(address,uint256,uint256)": TypedContractEvent<
      FundsDonatedEvent.InputTuple,
      FundsDonatedEvent.OutputTuple,
      FundsDonatedEvent.OutputObject
    >;
    FundsDonated: TypedContractEvent<
      FundsDonatedEvent.InputTuple,
      FundsDonatedEvent.OutputTuple,
      FundsDonatedEvent.OutputObject
    >;

    "GovernanceUpdated(address)": TypedContractEvent<
      GovernanceUpdatedEvent.InputTuple,
      GovernanceUpdatedEvent.OutputTuple,
      GovernanceUpdatedEvent.OutputObject
    >;
    GovernanceUpdated: TypedContractEvent<
      GovernanceUpdatedEvent.InputTuple,
      GovernanceUpdatedEvent.OutputTuple,
      GovernanceUpdatedEvent.OutputObject
    >;

    "MilestoneFundsReleased(uint256,uint256,address)": TypedContractEvent<
      MilestoneFundsReleasedEvent.InputTuple,
      MilestoneFundsReleasedEvent.OutputTuple,
      MilestoneFundsReleasedEvent.OutputObject
    >;
    MilestoneFundsReleased: TypedContractEvent<
      MilestoneFundsReleasedEvent.InputTuple,
      MilestoneFundsReleasedEvent.OutputTuple,
      MilestoneFundsReleasedEvent.OutputObject
    >;

    "ProjectCancelled(address)": TypedContractEvent<
      ProjectCancelledEvent.InputTuple,
      ProjectCancelledEvent.OutputTuple,
      ProjectCancelledEvent.OutputObject
    >;
    ProjectCancelled: TypedContractEvent<
      ProjectCancelledEvent.InputTuple,
      ProjectCancelledEvent.OutputTuple,
      ProjectCancelledEvent.OutputObject
    >;

    "RefundClaimed(address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "RefundsEnabled(uint256)": TypedContractEvent<
      RefundsEnabledEvent.InputTuple,
      RefundsEnabledEvent.OutputTuple,
      RefundsEnabledEvent.OutputObject
    >;
    RefundsEnabled: TypedContractEvent<
      RefundsEnabledEvent.InputTuple,
      RefundsEnabledEvent.OutputTuple,
      RefundsEnabledEvent.OutputObject
    >;
  };
}
