/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as milestoneGovernanceSol from "./MilestoneGovernance.sol";
export type { milestoneGovernanceSol };
export type { FundingEscrow } from "./FundingEscrow";
