/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFundingEscrow } from "./IFundingEscrow";
export type { MilestoneGovernance } from "./MilestoneGovernance";
